### PR TITLE
Add APT repo instructions and updated driver documentation

### PR DESCRIPTION
**Pull request by ardangelo**
New users should install from the APT driver repo instead of building from source. This eases onboarding and future updates.

Repo packages source is at https://github.com/ardangelo/beepy-ppa-source

Update the rest of the software documentation to the current state for the keyboard and display drivers.

### CODE REVIEW

**Comment by maxmbed** [comment]
It is likely that in my case I get a dpgk error during the installation of `sharp-drm` package. I am not sure how can I uninstall the old development sharp module. 

```
curl -s --compressed "https://ardangelo.github.io/beepy-ppa/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/beepy.gpg >/dev/null \
&& sudo curl -s --compressed -o /etc/apt/sources.list.d/beepy.list "https://ardangelo.github.io/beepy-ppa/beepy.list" \
&& sudo apt update \
&& sudo apt-get -y install beepy-kbd sharp-drm \
&& sudo shutdown -r now
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Get:3 https://ardangelo.github.io/beepy-ppa ./ InRelease [1,948 B]
Get:4 https://ardangelo.github.io/beepy-ppa ./ Packages [928 B]
Fetched 2,876 B in 2s (1,869 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
29 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  dctrl-tools dkms i2c-tools libi2c0 read-edid
Suggested packages:
  debtags menu libi2c-dev python-smbus
The following NEW packages will be installed:
  beepy-kbd dctrl-tools dkms i2c-tools libi2c0 read-edid sharp-drm
0 upgraded, 7 newly installed, 0 to remove and 29 not upgraded.
Need to get 627 kB of archives.
After this operation, 3,910 kB of additional disk space will be used.
Get:2 https://ardangelo.github.io/beepy-ppa ./ beepy-kbd 2.1-2 [333 kB]
Get:1 http://ftp.acc.umu.se/mirror/raspbian/raspbian bullseye/main armhf dctrl-tools armhf 2.24-3 [94.2 kB]
Get:3 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian bullseye/main armhf dkms all 2.8.4-3 [78.2 kB]
Get:5 https://ardangelo.github.io/beepy-ppa ./ sharp-drm 1.0-3 [18.3 kB]
Get:4 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libi2c0 armhf 4.2-1+b1 [10.4 kB]
Get:6 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf i2c-tools armhf 4.2-1+b1 [78.0 kB]
Get:7 http://mirrors.fe.up.pt/raspbian/raspbian bullseye/main armhf read-edid armhf 3.0.2-1.1 [14.9 kB]
Fetched 627 kB in 7s (96.1 kB/s)
Selecting previously unselected package dctrl-tools.
(Reading database ... 98478 files and directories currently installed.)
Preparing to unpack .../0-dctrl-tools_2.24-3_armhf.deb ...
Unpacking dctrl-tools (2.24-3) ...
Selecting previously unselected package dkms.
Preparing to unpack .../1-dkms_2.8.4-3_all.deb ...
Unpacking dkms (2.8.4-3) ...
Selecting previously unselected package libi2c0:armhf.
Preparing to unpack .../2-libi2c0_4.2-1+b1_armhf.deb ...
Unpacking libi2c0:armhf (4.2-1+b1) ...
Selecting previously unselected package i2c-tools.
Preparing to unpack .../3-i2c-tools_4.2-1+b1_armhf.deb ...
Unpacking i2c-tools (4.2-1+b1) ...
Selecting previously unselected package read-edid.
Preparing to unpack .../4-read-edid_3.0.2-1.1_armhf.deb ...
Unpacking read-edid (3.0.2-1.1) ...
Selecting previously unselected package beepy-kbd.
Preparing to unpack .../5-beepy-kbd_2.1-2_armhf.deb ...
Firmware version 2.1 passes module requirement
Unpacking beepy-kbd (2.1-2) ...
Selecting previously unselected package sharp-drm.
Preparing to unpack .../6-sharp-drm_1.0-3_armhf.deb ...
error: please uninstall the old development sharp module
dpkg: error processing archive /tmp/apt-dpkg-install-p3UiJ1/6-sharp-drm_1.0-3_armhf.deb (--unpack):
 new sharp-drm package pre-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 /tmp/apt-dpkg-install-p3UiJ1/6-sharp-drm_1.0-3_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```


```shell
sudo apt install sharp-drm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  sharp-drm
0 upgraded, 1 newly installed, 0 to remove and 29 not upgraded.
Need to get 0 B/18.3 kB of archives.
After this operation, 81.9 kB of additional disk space will be used.
(Reading database ... 98670 files and directories currently installed.)
Preparing to unpack .../sharp-drm_1.0-3_armhf.deb ...
error: please uninstall the old development sharp module
dpkg: error processing archive /var/cache/apt/archives/sharp-drm_1.0-3_armhf.deb (--unpack):
 new sharp-drm package pre-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/sharp-drm_1.0-3_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by ardangelo** [comment]
Hi, did you follow the instructions to remove the source build here? 
https://ardangelo.github.io/beepy-ppa/#cleaning-old-source-builds-of-drivers

**Comment by maxmbed** [comment]
> Hi, did you follow the instructions to remove the source build here? https://ardangelo.github.io/beepy-ppa/#cleaning-old-source-builds-of-drivers

Right, I did not. Installing sharp-drm work now. Thanks.

**Comment by sqfmi** [comment]
Merged, thanks!!!

**Pull request merged**
